### ISSUE TITLE
hupu project

### ISSUE THREAD

**Issue by mugglejohnny** [crossin/snippet#2]
在
for i in range(1, 160):
    print(i)
    url = 'https://bbs.hupu.com/bxj-postdate-' + str(i)
    r=rq.get(url, headers=h)
    r.encoding='utf8'
#     print(r.text)
    soup=BeautifulSoup(r.text, 'lxml')
    lis = soup.find(class_="show-list").find_all('li')

运行到i= 11时报错：
    lis = soup.find(class_="show-list").find_all('li')

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by crossin** [comment]
在代码里加上输出，把请求的页面和拿到的结果输出来看
如果是后面的页面，是需要加上登录后的cookie才能拿到的，注释里有说

**Comment by mugglejohnny** [comment]
我添加了自己的cookie还是只能到i=11,
输入就是您的那段代码加了自己的cookie：
import requests as rq
from bs4 import BeautifulSoup
import time
posts = []
h = {
    'referer': 'https://bbs.hupu.com/bxj-postdate-1',
    'user-agent': 'Mozilla/5.0 Chrome/66.0',
    'cookie':"Hm_lpvt_39fc58a7ab8a311f2f6ca4dc1222a96e", # 添加你的cookie，否则只能抓前几十页
}
for i in range(1, 160):
    print(i)
    url = 'https://bbs.hupu.com/bxj-postdate-' + str(i)
    r=rq.get(url, headers= h)
    r.encoding='utf8'
     print(r.text)
    soup=BeautifulSoup(r.text, 'lxml')
    lis = soup.find(class_="show-list").find_all('li')
    
    for li in lis:
        title = li.a.text.lower()
        if '吴' in title or '凡' in title or 'skr' in title or 'diss' in title or 'rap' in title or 'hiphop' in title or '嘻哈' in title or 'wyf' in title or 'cris' in title or '51' in title:
            p = int(li.a.get('href').strip('/.html'))
            r, v = li.find(class_='ansour').text.split('/')
            r = int(r.strip())
            v = int(v.strip())
            Post.create(pid=p, title=title, count_reply=r, count_view=v)
     time.sleep(1)

输出为：

1
2
3
4
5
6
7
8
9
10
11
Traceback (most recent call last):

  File "<ipython-input-25-287eff1acba7>", line 18, in <module>
    lis = soup.find(class_="show-list").find_all('li')

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by mugglejohnny** [comment]
我的输入为：
import requests as rq
from bs4 import BeautifulSoup
import time
posts = []
h = {
    'referer': 'https://bbs.hupu.com/bxj-postdate-1',
    'user-agent': 'Mozilla/5.0 Chrome/66.0',
    'cookie':"Hm_lpvt_39fc58a7ab8a311f2f6ca4dc1222a96e", # 添加你的cookie，否则只能抓前几十页
}
for i in range(1, 160):
    print(i)
    url = 'https://bbs.hupu.com/bxj-postdate-' + str(i)
    r=rq.get(url, headers= h)
    r.encoding='utf8'
     print(r.text)
    soup=BeautifulSoup(r.text, 'lxml')
    lis = soup.find(class_="show-list").find_all('li')
    
    for li in lis:
        title = li.a.text.lower()
        if '吴' in title or '凡' in title or 'skr' in title or 'diss' in title or 'rap' in title or 'hiphop' in title or '嘻哈' in title or 'wyf' in title or 'cris' in title or '51' in title:
            p = int(li.a.get('href').strip('/.html'))
            r, v = li.find(class_='ansour').text.split('/')
            r = int(r.strip())
            v = int(v.strip())
            Post.create(pid=p, title=title, count_reply=r, count_view=v)

输出为：
1
2
3
4
5
6
7
8
9
10
11
Traceback (most recent call last):

  File "<ipython-input-25-287eff1acba7>", line 18, in <module>
    lis = soup.find(class_="show-list").find_all('li')

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by mugglejohnny** [comment]
还有一个小问题是：
line = ec.Line('时间统计', width=1000)
然后报错说ec没有define

**Comment by mugglejohnny** [comment]
您好 第一个问题已经解决了，
第二个问题line = ec.Line('时间统计', width=1000)中，
ec报错没有定义，老师可以帮忙解决一下吗？
